image: python:3.10

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Starting test stage at $(date)"
    - pip install -r requirements.txt
    - export PYTHONPATH="$PYTHONPATH:."
    - pytest

build:
  stage: build
  script:
    - echo "Starting build stage at $(date)"
    - echo "Build completed"

deploy:
  stage: deploy
  script:
    - echo "Starting deploy stage at $(date)"
    - echo "Deploy completed"
