stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - echo "Starting test stage at $(date)"
    - pip install -r requirements.txt
    - echo "Running tests at $(date)"
    - PYTHONPATH=. pytest
    - echo "Test stage completed at $(date)"

build:
  stage: build
  script:
    - echo "Starting build stage at $(date)"
    - echo "Building the application..."
    - echo "Build stage completed at $(date)"

deploy:
  stage: deploy
  script:
    - echo "Starting deploy stage at $(date)"
    - echo "Deploying the application..."
    - echo "Deploy stage completed at $(date)"
